# Generated by Django 2.0.6 on 2018-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20180601_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_no']},
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
